### ISSUE TITLE
Linker Error `Aws::Cryptosdk::KmsKeyring::Builder::Build`

### ISSUE THREAD

**Issue by RShaggy** [awslabs/aws-encryption-sdk-c#350]
Compiled the code using the steps for Windows & Linux, in our code we get a linker error saying;

`undefined reference to Aws::Cryptosdk::KmsKeyring::Builder::Build(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) cons'`

We have the following Dependencies;

- aws-cpp-sdk-core.lib 
- aws-cpp-sdk-kinesis.lib 
- aws-cpp-sdk-kms.lib 
- aws-c-event-stream.lib 
- aws-encryption-sdk.lib 
- aws-encryption-sdk-cpp.lib 
- aws-c-common.lib

Running `nm -a externals/aws_encryption_sdk_cpp_0.1.0/lib64/libaws-encryption-sdk-cpp.so|grep Builder|grep Build` we get 6 hits;

`00000000000410e4 T _ZN3Aws9Cryptosdk10KmsKeyring7Builder13WithKmsClientERKSt10shared_ptrINS_3KMS9KMSClientEE
0000000000041088 T _ZN3Aws9Cryptosdk10KmsKeyring7Builder14WithGrantTokenERKSbIcSt11char_traitsIcENS_9AllocatorIcEEE
0000000000041024 T _ZN3Aws9Cryptosdk10KmsKeyring7Builder15WithGrantTokensERKSt6vectorISbIcSt11char_traitsIcENS_9AllocatorIcEEENS6_IS8_EEE
00000000000410b6 T _ZN3Aws9Cryptosdk10KmsKeyring7Builder18WithClientSupplierERKSt10shared_ptrINS1_14ClientSupplierEE
0000000000040f22 T _ZNK3Aws9Cryptosdk10KmsKeyring7Builder14BuildDiscoveryEv
0000000000040a7c T _ZNK3Aws9Cryptosdk10KmsKeyring7Builder5BuildERKSbIcSt11char_traitsIcENS_9AllocatorIcEEERKSt6vectorIS7_NS5_IS7_EEE `

Would appreciate any insights you might have, maybe we're linking to the wrong library but from the nm results it seems that the function is there.

Thanks

**Comment by johnwalker** [comment]
Hi Shaggy, do you also get an error when you build the `kms_discovery.cpp` example? The error you mentioned sounds like `aws-encryption-sdk-cpp` isn't linked. Please double check that you are linking to `aws-encryption-sdk` and `aws-encryption-sdk-cpp`.

Would you try running this command in the examples directory, and let us know if you get a similar error?

```
g++ -o kms_discovery kms_discovery.cpp -lcrypto -laws-encryption-sdk -laws-encryption-sdk-cpp -laws-c-common -laws-cpp-sdk-kms -laws-cpp-sdk-core
```

**Comment by RShaggy** [comment]
Running the command on the same machine the build was made on works, running it on a different machine does not. I suspect this is the issue, our build system for our project is CentOS and the library was built on Amazon Linux AMI.

**Comment by david-koenig** [comment]
We have not yet tried building the AWS Encryption SDK for C on CentOS 6, so at this point it is not an officially supported operating system. I have created #351 to add support for it, and I am resolving this issue in favor of that one.
